function YelpCategories(){
    const cats = `Afghan (afghani, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
    African (african, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
    Senegalese (senegalese, [BE, CA, IT, US, FR])
    South African (southafrican, [BE, CA, AU, IT, US, FR])
    American (New) (newamerican, [US, GB, NO, DK, SE, IE])
    American (Traditional) (tradamerican, All)
    Andalusian (andalusian, [IT, ES])
    Arabic (arabian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
    Arab Pizza (arabpizza, [BR])
    Argentine (argentine, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
    Armenian (armenian, [GB, ES, US, TR, FR, PL, BE, IT, AR, CZ])
    Asian Fusion (asianfusion, All)
    Asturian (asturian, [ES])
    Australian (australian, All)
    Austrian (austrian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
    Baguettes (baguettes, [PT, SE, TR, DE, MX, NO, IT, CZ])
    Bangladeshi (bangladeshi, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
    Barbeque (bbq, [AR, AT, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
    Basque (basque, [AR, AT, BE, BR, CA, CH, CL, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, TW, US])
    Bavarian (bavarian, [DE, CH, AT])
    Beer Garden (beergarden, [DE, CZ, CH, AT])
    Beer Hall (beerhall, [DE, CH, AT])
    Beisl (beisl, [AT])
    Belgian (belgian, All)
    Flemish (flemish, [FR])
    Bistros (bistros, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW])
    Black Sea (blacksea, [TR])
    Brasseries (brasseries, [AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
    Brazilian (brazilian, All)
    Brazilian Empanadas (brazilianempanadas, [BR])
    Central Brazilian (centralbrazilian, [BR])
    Northeastern Brazilian (northeasternbrazilian, [BR])
    Northern Brazilian (northernbrazilian, [BR])
    Rodizios (rodizios, [BR, PT, AR])
    Breakfast & Brunch (breakfast_brunch, All)
    Pancakes (pancakes, All)
    British (british, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
    Buffets (buffets, All)
    Bulgarian (bulgarian, [AR, AT, AU, BE, CH, CL, CZ, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, PH, PL, PT, SE, TW, US])
    Burgers (burgers, All)
    Burmese (burmese, [AR, AT, AU, BE, BR, CA, CH, CL, DE, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
    Cafes (cafes, [AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
    Themed Cafes (themedcafes, [GB, SG, AU, US, SE, DE, NL, MY, AT, BE, HK, CA, PH, NO, JP, NZ, TW, DK, FR, PL, MX, FI, AR, IE, CH, CL])
    Cafeteria (cafeteria, [AR, AT, AU, BE, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IT, JP, MX, MY, NL, NO, PH, PL, PT, TR, TW, US])
    Cajun/Creole (cajun, [AR, AT, BE, BR, CA, CH, CL, CZ, DE, DK, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, TR, TW, US])
    Cambodian (cambodian, [AR, AT, AU, BE, BR, CA, CH, CL, DE, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
    Canadian (New) (newcanadian, [CA])
    Canteen (canteen, [JP, DK, DE, NL, AT, PL, BE, FI, IT, NO, CZ, CH])
    Caribbean (caribbean, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
    Dominican (dominican, [US])
    Haitian (haitian, [CA, US])
    Puerto Rican (puertorican, [US])
    Trinidadian (trinidadian, [US])
    Catalan (catalan, [ES, PT, TR, FR, US, MX, IT, AR, CL])
    Cheesesteaks (cheesesteaks, [GB, CA, AU, US, IE, NL, PL])
    Chicken Shop (chickenshop, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
    Chicken Wings (chicken_wings, [AR, AT, AU, BR, CA, CZ, DE, GB, HK, IE, MX, MY, NZ, PH, PL, SE, SG, TR, TW, US])
    Chilean (chilean, [FR, BR, FI, CL])
    Chinese (chinese, All)
    Cantonese (cantonese, [GB, SG, AU, US, SE, NL, MY, BE, CA, HK, JP, NZ, TW, FR, IT, AR])
    Congee (congee, [HK, TW, SG, MY])
    Dim Sum (dimsum, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
    Fuzhou (fuzhou, [HK, TW, SG, MY])
    Hainan (hainan, [HK, SG, PH, US, MY])
    Hakka (hakka, [HK, CA, SG, TW, PH, MY])
    Henghwa (henghwa, [HK, TW, SG, MY])
    Hokkien (hokkien, [HK, TW, SG, MY])
    Hunan (hunan, [HK, TW, SG, FR, MY])
    Pekinese (pekinese, [HK, JP, SG, TW, IT, FR, MY])
    Shanghainese (shanghainese, [JP, AU, SG, TW, SE, US, FR, MY, BE, HK, IT])
    Szechuan (szechuan, [GB, JP, AU, NZ, SG, TW, US, FR, MY, HK, IE])
    Teochew (teochew, [HK, TW, SG, MY])
    Comfort Food (comfortfood, [JP, CA, MX, AR, FI, US, CL])
    Corsican (corsican, [BE, FR])
    Creperies (creperies, All)
    Cuban (cuban, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TW, US])
    Curry Sausage (currysausage, [DE, CH, AT])
    Cypriot (cypriot, [DE, CH, AT])
    Czech (czech, [GB, AU, DK, SE, US, FR, DE, PL, BE, CA, FI, IT, NO, IE, CZ])
    Czech/Slovakian (czechslovakian, [MX, PT, AR])
    Danish (danish, [FR, NO, DK, SE])
    Delis (delis, [AR, AT, AU, BR, CA, CH, CZ, DE, DK, ES, FI, GB, HK, IE, JP, MX, MY, NO, NZ, PH, PL, SG, TR, TW, US])
    Diners (diners, [AR, AT, BE, BR, CA, CH, CL, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SG, TR, TW, US])
    Dinner Theater (dinnertheater, [AR, AT, AU, BR, CA, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IE, MX, MY, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
    Dumplings (dumplings, [JP, NZ, SG, AU, GB, DE, NL, AT, PL, BE, CA, IE, CH])
    Eastern European (eastern_european, [AU, NO, DK, FR, CZ])
    Eritrean (eritrean, [IT, US, DE, CH, AT])
    Ethiopian (ethiopian, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, TW, US])
    Fast Food (hotdogs, All)
    Filipino (filipino, [AR, AT, AU, BE, BR, CA, CH, CL, DE, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
    Fischbroetchen (fischbroetchen, [DE])
    Fish & Chips (fishnchips, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TR, TW, US])
    Flatbread (flatbread, [DK, DE, CH, AT, PL])
    Fondue (fondue, [AR, AT, AU, BE, BR, CA, CH, CL, DE, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
    Food Court (food_court, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, US])
    Food Stands (foodstands, All)
    Freiduria (freiduria, [CL, MX, ES, AR])
    French (french, All)
    Alsatian (alsatian, [FR, DE])
    Auvergnat (auvergnat, [FR])
    Berrichon (berrichon, [FR])
    Bourguignon (bourguignon, [FR])
    Mauritius (mauritius, [BE, CA, CZ, ES, FI, FR, GB, HK, IE, IT, MY, NL, PH, PT, SE, SG, TW, US])
    Nicoise (nicois, [FR])
    Provencal (provencal, [FR])
    Reunion (reunion, [BE, CA, CZ, ES, FI, FR, GB, HK, IE, IT, MY, NL, PH, PT, SE, SG, TW, US])
    French Southwest (sud_ouest, [BE, FR])
    Galician (galician, [PT, ES])
    Game Meat (gamemeat, [AT, AU, BE, CH, CZ, DE, DK, ES, FR, GB, IE, IT, NL, NO, NZ, PL, SE, SG, US])
    Gastropubs (gastropubs, All)
    Georgian (georgian, [GB, US, DE, AT, PL, FI, CZ, CH])
    German (german, All)
    Baden (baden, [DE])
    Eastern German (easterngerman, [DE])
    Franconian (franconian, [DE])
    Hessian (hessian, [DE])
    Northern German (northerngerman, [DE])
    Palatine (palatine, [DE])
    Rhinelandian (rhinelandian, [DE])
    Giblets (giblets, [TR])
    Gluten-Free (gluten_free, All)
    Greek (greek, All)
    Guamanian (guamanian, [AT, AU, BE, BR, CA, CH, CZ, DE, DK, ES, FI, GB, HK, IE, IT, MY, NL, NO, NZ, PH, PT, SE, SG, TW, US])
    Halal (halal, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
    Hawaiian (hawaiian, [AR, AT, BE, BR, CA, CH, CL, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
    Heuriger (heuriger, [AT])
    Himalayan/Nepalese (himalayan, All)
    Honduran (honduran, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
    Hong Kong Style Cafe (hkcafe, [HK, CA, TW, US])
    Hot Dogs (hotdog, All)
    Hot Pot (hotpot, [JP, SG, TW, SE, US, FR, MY, HK, CA, BR, PH])
    Hungarian (hungarian, All)
    Iberian (iberian, [CA, PT, US])
    Indian (indpak, All)
    Indonesian (indonesian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
    International (international, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, JP, MX, NL, NO, NZ, PL, PT, SE, SG, TW])
    Irish (irish, All)
    Island Pub (island_pub, [SE])
    Israeli (israeli, [DE, CZ, CH, AT])
    Italian (italian, All)
    Abruzzese (abruzzese, [IT])
    Altoatesine (altoatesine, [IT])
    Apulian (apulian, [FR, IT])
    Calabrian (calabrian, [FR, IT, US])
    Cucina campana (cucinacampana, [IT])
    Emilian (emilian, [IT])
    Friulan (friulan, [IT])
    Ligurian (ligurian, [FR, IT])
    Lumbard (lumbard, [IT])
    Napoletana (napoletana, [FR, CZ, IT])
    Piemonte (piemonte, [FR, IT])
    Roman (roman, [FR, IT, JP])
    Sardinian (sardinian, [FR, IT, US])
    Sicilian (sicilian, [IT, US, FR, CZ, PL])
    Tuscan (tuscan, [FR, IT, US])
    Venetian (venetian, [FR, IT])
    Japanese (japanese, All)
    Blowfish (blowfish, [JP])
    Conveyor Belt Sushi (conveyorsushi, [JP, SG, TW, SE, US, DE, NL, AT, PL, BE, HK, IT, CH])
    Donburi (donburi, [HK, JP, TW])
    Gyudon (gyudon, [JP])
    Oyakodon (oyakodon, [JP])
    Hand Rolls (handrolls, [TW, BR])
    Horumon (horumon, [JP, TW])
    Izakaya (izakaya, [JP, NZ, AU, SG, TW, US, HK, BR, MX])
    Japanese Curry (japacurry, [HK, JP, TW, SG, US])
    Kaiseki (kaiseki, [JP, TW])
    Kushikatsu (kushikatsu, [JP])
    Oden (oden, [JP, TW])
    Okinawan (okinawan, [JP])
    Okonomiyaki (okonomiyaki, [JP, TW])
    Onigiri (onigiri, [JP, TW])
    Ramen (ramen, All)
    Robatayaki (robatayaki, [HK, JP, TW])
    Soba (soba, [JP, TW])
    Sukiyaki (sukiyaki, [JP, TW])
    Takoyaki (takoyaki, [JP, TW])
    Tempura (tempura, [JP, TW, SG])
    Teppanyaki (teppanyaki, [JP, NZ, AU, SG, TW, US, HK, MX])
    Tonkatsu (tonkatsu, [JP, TW, SG])
    Udon (udon, [HK, JP, TW, NO, DK, SE, FI])
    Unagi (unagi, [JP, TW])
    Western Style Japanese Food (westernjapanese, [JP, TW, SG])
    Yakiniku (yakiniku, [JP, TW, SG])
    Yakitori (yakitori, [JP, TW, SG])
    Jewish (jewish, [DE, IT, PL])
    Kebab (kebab, All)
    Kopitiam (kopitiam, [SG, MY])
    Korean (korean, All)
    Kosher (kosher, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
    Kurdish (kurdish, [NO, SE])
    Laos (laos, [AU])
    Laotian (laotian, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
    Latin American (latin, All)
    Colombian (colombian, [ES, US, FR, BE, CA, MX, FI, AR, CL])
    Salvadoran (salvadoran, [CA, US])
    Venezuelan (venezuelan, [US, CA, AR, ES, PT, FR, CL])
    Live/Raw Food (raw_food, All)
    Lyonnais (lyonnais, [BE, FR])
    Malaysian (malaysian, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
    Mamak (mamak, [AU, MY])
    Nyonya (nyonya, [AU, MY])
    Meatballs (meatballs, [BE, FR, NL, TR])
    Mediterranean (mediterranean, All)
    Falafel (falafel, [AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, SE, SG, TR, TW, US])
    Mexican (mexican, All)
    Eastern Mexican (easternmexican, [MX])
    Jaliscan (jaliscan, [MX])
    Northern Mexican (northernmexican, [MX])
    Oaxacan (oaxacan, [MX])
    Pueblan (pueblan, [MX])
    Tacos (tacos, [MX, US])
    Tamales (tamales, [MX])
    Yucatan (yucatan, [MX])
    Middle Eastern (mideastern, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
    Egyptian (egyptian, [BE, CA, IT, US, FR])
    Lebanese (lebanese, [AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, IE, IT, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
    Milk Bars (milkbars, [AU, PL])
    Modern Australian (modern_australian, [AU])
    Modern European (modern_european, All)
    Mongolian (mongolian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
    Moroccan (moroccan, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
    New Mexican Cuisine (newmexican, [US])
    New Zealand (newzealand, [NZ])
    Nicaraguan (nicaraguan, [AT, AU, BE, BR, CA, CH, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
    Night Food (nightfood, [NO, DK, SE, TR, PL])
    Nikkei (nikkei, [BR, MX, ES, AR, CL])
    Noodles (noodles, [AR, AU, BE, BR, CA, CL, CZ, DK, ES, FI, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
    Norcinerie (norcinerie, [IT])
    Open Sandwiches (opensandwiches, [TR, NO, DK, SE])
    Oriental (oriental, [PT, FR, DE, CH, AT, PL])
    PF/Comercial (pfcomercial, [BR])
    Pakistani (pakistani, All)
    Pan Asian (panasian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
    Parent Cafes (eltern_cafes, [DE, CH, AT])
    Parma (parma, [AU])
    Persian/Iranian (persian, All)
    Peruvian (peruvian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, TW, US])
    Pita (pita, [TR])
    Pizza (pizza, All)
    Polish (polish, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TR, TW, US])
    Pierogis (pierogis, [PL])
    Polynesian (polynesian, [US])
    Pop-Up Restaurants (popuprestaurants, [GB, AU, SG, US, SE, DE, NL, MY, BE, CA, HK, PH, NO, NZ, TW, DK, FR, IE])
    Portuguese (portuguese, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
    Alentejo (alentejo, [PT])
    Algarve (algarve, [PT])
    Azores (azores, [PT])
    Beira (beira, [PT])
    Fado Houses (fado_houses, [PT])
    Madeira (madeira, [PT])
    Minho (minho, [PT])
    Ribatejo (ribatejo, [PT])
    Tras-os-Montes (tras_os_montes, [PT])
    Potatoes (potatoes, [DE, AU, CH, AT])
    Poutineries (poutineries, [CA, US])
    Pub Food (pubfood, [AU])
    Rice (riceshop, [TR, JP])
    Romanian (romanian, [ES, FR, DE, AT, PL, BE, CZ, CH])
    Rotisserie Chicken (rotisserie_chicken, [NZ, AU, ES, PT, FR, NL, PL, BE, BR, MX, IT, AR, CL])
    Russian (russian, All)
    Salad (salad, All)
    Sandwiches (sandwiches, All)
    Scandinavian (scandinavian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TR, TW, US])
    Schnitzel (schnitzel, [DE, CH, AT, PL])
    Scottish (scottish, [GB, CA, IE, US, DE, CH, AT])
    Seafood (seafood, All)
    Serbo Croatian (serbocroatian, [SE, FR, DE, AT, PL, BE, IT, AR, CZ, CH, CL])
    Signature Cuisine (signature_cuisine, [ES, DK, PT, SE, MX, NO, AR, CL])
    Singaporean (singaporean, [AR, AT, AU, BE, BR, CA, CH, CL, DE, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
    Slovakian (slovakian, [GB, AU, US, FR, PL, BE, CA, IT, IE, CZ])
    Somali (somali, [IT, US, DE, CH, AT, PL])
    Soul Food (soulfood, [GB, ES, SE, US, NL, PL, CA, NO, IE])
    Soup (soup, All)
    Southern (southern, [GB, NZ, SE, TR, US, NL, PL, CA, IE])
    Spanish (spanish, All)
    Arroceria / Paella (arroceria_paella, [ES])
    Sri Lankan (srilankan, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
    Steakhouses (steak, All)
    Supper Clubs (supperclubs, [GB, CA, ES, US])
    Sushi Bars (sushi, All)
    Swabian (swabian, [DE, CH, AT])
    Swedish (swedish, [SE])
    Swiss Food (swissfood, [MX, ES, AR, DE, CZ, CH, CL])
    Syrian (syrian, All)
    Tabernas (tabernas, [TR, PT, ES])
    Taiwanese (taiwanese, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
    Tapas Bars (tapas, [AR, AT, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TR, TW, US])
    Tapas/Small Plates (tapasmallplates, All)
    Tavola Calda (tavolacalda, [IT])
    Tex-Mex (tex-mex, [AR, AT, BE, BR, CA, CH, CL, CZ, DE, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TR, TW, US])
    Thai (thai, All)
    Traditional Norwegian (norwegian, [FR, NO])
    Traditional Swedish (traditional_swedish, [FI, SE])
    Trattorie (trattorie, [IT, AR, FR, CL, CH, PL])
    Turkish (turkish, All)
    Chee Kufta (cheekufta, [TR, DE])
    Gozleme (gozleme, [TR])
    Homemade Food (homemadefood, [TR])
    Lahmacun (lahmacun, [TR])
    Ottoman Cuisine (ottomancuisine, [TR])
    Turkish Ravioli (turkishravioli, [TR])
    Ukrainian (ukrainian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
    Uzbek (uzbek, [CZ, US])
    Vegan (vegan, All)
    Vegetarian (vegetarian, All)
    Venison (venison, [GB, NZ, AU, SG, DK, PL, CA, IT, NO, IE, CZ])
    Vietnamese (vietnamese, All)
    Waffles (waffles, All)
    Wok (wok, [AT, BE, CH, CL, CZ, DE, DK, ES, FI, FR, MX, MY, NL, NO, PH, PT, SE])
    Wraps (wraps, [SE, US, NO, PT, DK, TR, CZ])
    Yugoslav (yugoslav, [BE, AU, IT, PT, SE, FR])`
    
    const splitCats = cats.split('\n')
    const inUS = splitCats.filter(x=>(x.includes('US') || x.includes('All')))
    let newCats = []
    for (let i = 0 ; i <inUS.length ; i++){
        newCats.push(inUS[i].slice(0,inUS[i].indexOf('(')).trim())
    }

    for(let i = 50 ; i < newCats.length ; i+=50){
        console.log(newCats.slice(i-50 , i))
    }

}

YelpCategories()
